In [1]:
import numpy as np

In [44]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [45]:
print(np.__version__)

1.26.4


In [9]:
### Crear Matrices de Numpy ###

In [46]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
### Para crear un ndarray. podemos pàsar una lista. tupla, o cualquier objeto similar  una matriz al array() metodo y se convertira en ndarray:

In [47]:
### ejemplo con una tupla

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [48]:
#### Dimenciones en Matrices
### Matriz Anidada : Son Matrices que tienen matrices como elementos
### Matrices 0-D
###Las Matrices 0-D, o escalares, son elementos de una Matriz. Cada Valor de una Matriz es una matriz 0-D
### Ejemplo: Crear una Matriz 0-D con valor 42
arr=np.array(42)
print(arr)




42


In [49]:
### Matrices 1-D : Una Mariz que tiene matrices 0-D como elementos se llama Matriz unidimensional o 1-D
### Estas son las matrices mas comunes y basicas:
### Ejemplo cree una matriz 1-D que contenga los valores 1,2,3,4,5:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [50]:
### Matrices 2-D
### Una Matriz que tiene matrices 1-D como elementos se llama Matriz 2-D, se utilizan a manudo para representar matrices o tensores de segundo orden
### numpy tiene un submodulo completo dedicado a operaciones matriciales llamado numpy.mat
### Ejemplo: Cree una matriz 2-D que contenga dos matrices con los valores 1,2,3 y 4,5,6
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [51]:
### Matrices 3-D
### Una matriz que tiene matrices 2D(matrices) como elementos se llama matriz 3D
### Se utiizan a menudo para representar un tensor de tercer orden
### Ejemplo: Crear una mariz 3D con dos matrices 2D, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6:

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [53]:
### Verificar numero de dimensiones
### Numpy Arrays proporciona el ndim atributo que devuelve un numero entero que nos dice cuantas dimensiones tiene la matriz
### Ejemplo: Compruebe cuantas dimensiones tienen las matrices

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [54]:
### Matrices de dimensiones superiores
### Una Matriz puede tener cualquier numero de dimensiones. Cuando se crea la matriz, puede definir el numero de dimensiones
### Utilizando el ndmin argumento.
### Ejemplo : Crear una matriz de 5 dimensiones y verifique que tenga 5 dimensiones

arr = np.array([1,2,3,4], ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


In [42]:
l=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],)
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [26]:
print(l.ndim)

3


In [55]:
l2=np.array([[[1,2,3,0],[4,5,6,0],[7,8,9,0]],[[1,2,3,0],[4,5,6,0],[7,8,9,0]],[[1,2,3,0],[4,5,6,0],[7,8,9,0]]])
print(l)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [37]:
print(l2.ndim)

3
