Ordenar matrices
Ordenar significa poner elementos en una secuencia ordenada .

Secuencia ordenada es cualquier secuencia que tiene un orden correspondiente a elementos, como numérico o alfabético, ascendente o descendente.

El objeto NumPy ndarray tiene una función llamada sort()que ordenará una matriz específica.

In [1]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

## Nota: Este método devuelve una copia de la matriz, sin modificar la matriz original.

[0 1 2 3]


In [9]:
### Otro Ejemplo
import numpy as np

arr = np.array([3, 2, 0, 1])

newarray = np.sort(arr)
print(newarray)
print(newarray.base) ### El resultado es none, por tanto se determina que es una copia del array original

[0 1 2 3]
None


In [10]:
### También puedes ordenar matrices de cadenas o cualquier otro tipo de datos:
### Ejemplo Ordene la matriz alfabéticamente:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [11]:
### Ejemplo Ordenar una matriz booleana:
import numpy as np

arr = np.array([True, False, True, False, False, False])

print(np.sort(arr))



[False False False False  True  True]


In [13]:
### Ordenar una Matriz 2-D
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]
