In [1]:
import numpy as np

In [14]:
### Acceder a los elementos de la Matriz
### La indexacion de matrices es lo mismo que acceder a un elemento de matriz, usando su indice
### los indices en las matrices de numpy comienzan en 0, lo que significa que es el primer elemento.
### Ejemplo
arr=np.array([1,2,3,4])
print(arr[0])

arr = np.array([1, 2, 3, 4])

print(arr[1])

1
2


In [5]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [15]:
### Acceder a Matrices 2-D
### Para acceder a elementos de matrices 2-D, podemos usar numeros enteros separados por comenas que representan la dimension y el indice
### del elemento.
### Piense en matrices 2D como una tabla con filas y columnas, donde la dimensión representa la fila y el índice representa la columna.
### Ejemplo
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 3]) ### primer argumento fila, segundo columna


2nd element on 1st row:  9


In [9]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [11]:
### Acceder a matrices 3-D
### Para acceder a elementos de matrices 3-D, podemos usar números enteros 
### separados por comas que representan las dimensiones y el índice del elemento.
arr = np.array([[[1, 2, 3], 
                 [4, 5, 6]], 
                
                [[7, 8, 9], 
                 [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2]) ### el primer indice indica la primera dimension ( o primera Matriz), 
### el segundo la fila de la matruz y el tercero la columna de la matriz

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [13]:
### Indexacion Negativa
### utilice indexacion negativa para acceder a una mtr4iz desde el final
### Ejemplo

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -2])


Last element from 2nd dim:  9


#### Indexing


Un problema común es seleccionar los elementos de un array de acuerdo a algún criterio.

Llamamos "indexing" a la operación que resuelve el problema de acceder a los elementos de un array con algún criterio.

Existen tres tipos de indexing en Numpy:

#### Array Slicing: accedemos a los elementos con los parámetros start,stop,step. Por ejemplo my_array[0:5:-1]

#### Fancy Indexing: creamos una lista de índices y la usamos para acceder a ciertos elementos del array: my_array[[3,5,7,8]]

#### Boolean Indexing: creamos una "máscara booleana" (un array o lista de True y False) para acceder a ciertos elementos: my_array[my_array > 4]

Veamos algunos ejemplo:

Creamos un array de una dimensión usando el método np.arange que devuelve valores espaciados uniformemente dentro de un intervalo dado.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

In [2]:
import numpy as np
one_d_array = np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Start = 1:  empezamos por el segundo elemento
# Stop: No está definido, entonces llegamos hasta el final.
# Step: El paso o distancia entre los elementos es 2.
one_d_array[1::2]

array([1, 3, 5, 7, 9])

In [8]:
# Start: No está definido, entonces comenzamos desde el primero.
# Stop: No está definido, entonces llegamos hasta el final.
# Step = -1, para invertir el orden del array
one_d_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
# Si queremos hacer slicing en orden invertido
one_d_array[7:2:-1]  

array([7, 6, 5, 4, 3])

In [12]:
### Slicing sobre arrays de más dimensiones
### Cuando tenemos más de una dimensión, podemos hacer slicing sobre cada una de ellas separándolas con una coma.

### Veamos algunos ejemplos:

rng = np.random.default_rng()
l = 0
h = 10
s = (3,4)

two_d_array = rng.uniform(l,h,s)
print(two_d_array)



[[7.39851867 5.92639919 5.9953801  9.99938709]
 [6.95659348 5.55626919 7.65556856 3.02551136]
 [5.25207193 3.73378137 9.09307084 6.26014991]]


In [13]:
# Los dos puntos ( : ) indican que accedemos a todos los elementos de cada fila 
# y el cero después de la coma indica que sólamente lo hacemos para la columna 0 (la primera).
two_d_array[:, 0]

array([7.39851867, 6.95659348, 5.25207193])

In [14]:
# Accedemos a la tercer fila
two_d_array[2, :]

array([5.25207193, 3.73378137, 9.09307084, 6.26014991])

In [16]:
# Otra forma de acceder a la tercer fila
two_d_array[2]

array([5.25207193, 3.73378137, 9.09307084, 6.26014991])

In [19]:
# Todas la filas, un slice de la segunda y tercer columna (índices 1 y 2)
two_d_array[:, 1:3]

array([[5.92639919, 5.9953801 ],
       [5.55626919, 7.65556856],
       [3.73378137, 9.09307084]])

In [20]:
# todas las filas, todas las columnas listadas en orden inverso
two_d_array[:, ::-1]

array([[9.99938709, 5.9953801 , 5.92639919, 7.39851867],
       [3.02551136, 7.65556856, 5.55626919, 6.95659348],
       [6.26014991, 9.09307084, 3.73378137, 5.25207193]])

In [21]:
print(two_d_array.ndim)

2


In [23]:
import numpy as np  ### Slicing para una matriz de 3 dimensiones
y = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(y.ndim)
print(y)

3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
y[0,:] ### Me trae unicamente la primera matriz, completa

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
y[:,:,1:3] ### Me trae todas las matrices, todas las filas de cada una, y un slicing de la columna 1 y 2.

array([[[2, 3],
        [5, 6]],

       [[2, 3],
        [5, 6]]])

In [27]:
y[0,0,2] ### Me trae la primera matriz, la primera fila, el tercer elemento, que es 3.

3

In [28]:
y[0,::-1,1:3] ### Me trae la primera matriz, todas las filas en orden inverso y un slicing de la columna 1 y 2.

array([[5, 6],
       [2, 3]])

#### Fancy Indexing


Esta técnica consiste en generar listas que contienen los índices de los elementos que queremos seleccionar y utilizar estas listas para indexar.

Veamos algunos ejemplos:

In [30]:
print(two_d_array)

[[7.39851867 5.92639919 5.9953801  9.99938709]
 [6.95659348 5.55626919 7.65556856 3.02551136]
 [5.25207193 3.73378137 9.09307084 6.26014991]]


In [31]:

# nos quedamos con todas las columnas y las filas 1, 3, 2 y repetimos la 1 (índices 0,2,1,0)
lista_indices_filas = [0, 2, 1, 0]
two_d_array[lista_indices_filas]

array([[7.39851867, 5.92639919, 5.9953801 , 9.99938709],
       [5.25207193, 3.73378137, 9.09307084, 6.26014991],
       [6.95659348, 5.55626919, 7.65556856, 3.02551136],
       [7.39851867, 5.92639919, 5.9953801 , 9.99938709]])

In [32]:
# nos quedamos con todas las filas y las columnas 3, 4, 2, y reptimos la 3 (índices 2,3,1,2)
lista_indices_columnas = [2, 3, 1, 2]
two_d_array[:, lista_indices_columnas]

array([[5.9953801 , 9.99938709, 5.92639919, 5.9953801 ],
       [7.65556856, 3.02551136, 5.55626919, 7.65556856],
       [9.09307084, 6.26014991, 3.73378137, 9.09307084]])

In [33]:
# y ahora seleccionamos tanto filas como columnas, combinando los dos casos anteriores
two_d_array[lista_indices_filas, lista_indices_columnas]


### Observemos que al pasar las dos listas, estamos seleccionando los elementos
### (0, 2), (2, 3), (1, 1) y (0,2)

### Se cumple que `indice_elem_i = (lista_indices_filas[i], lista_indices_columnas[i])`

array([5.9953801 , 6.26014991, 5.55626919, 5.9953801 ])

#### Boolean Indexing
volver a TOC

Esta técnica se basa en crear una "máscara booleana", que es una lista de valores True y False que sirve para seleccionar sólo los elementos cuyo índice coincide con un valor True.

Veamos algunos ejemplos sobre two_d_array:

In [34]:
print(two_d_array)

[[7.39851867 5.92639919 5.9953801  9.99938709]
 [6.95659348 5.55626919 7.65556856 3.02551136]
 [5.25207193 3.73378137 9.09307084 6.26014991]]


In [35]:
### Vamos a seleccionar los elementos que sean mayores que 5. Para esos creamos uma máscara con esa condición:

mask_great_5 = two_d_array > 5
print(mask_great_5)

[[ True  True  True  True]
 [ True  True  True False]
 [ True False  True  True]]


La máscara tiene valor True en aquellos elementos de two_d_array con valor mayor a 5, y False en los que tienen valor menor o igual que 5.

Ahora usemos esa máscara para seleccionar los elementos que cumplen esa condición, o sea los que tienen valor True en la máscara:

In [36]:
two_d_array[mask_great_5]

array([7.39851867, 5.92639919, 5.9953801 , 9.99938709, 6.95659348,
       5.55626919, 7.65556856, 5.25207193, 9.09307084, 6.26014991])

Definamos ahora una condición más compleja: vamos a seleccionar los elementos que sean mayores que 5 y menores que 8

In [37]:
mask_great_5_less_8 = (two_d_array > 5) & (two_d_array < 8)
print(mask_great_5_less_8)

[[ True  True  True False]
 [ True  True  True False]
 [ True False False  True]]


Ahora usemos esa máscara para seleccionar los elementos que cumplen esa condición, o sea los que tienen valor True en la máscara:

In [38]:
two_d_array[mask_great_5_less_8]

array([7.39851867, 5.92639919, 5.9953801 , 6.95659348, 5.55626919,
       7.65556856, 5.25207193, 6.26014991])