In [19]:
### Slicing significa tomar elementos de un indice determinado a otro indice determinado
### Pasamos segmentos en lugar de indice asi: [start:end]
### Tambien se pueden definir el paso asi [start:end:step]
### Si no pasamos el inicio de considera cero
### Si no pasamos el fin de la longitud considerada de la matriz en esa dimension
### si no pasamos el paso se considera 1
### Ejemplo: Corte elementos del indice 1 al indice 5 de la siguiente matriz

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])



[2 3 4 5]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [20]:
### Negative Slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:
### STEP

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])### El ultimo argumento es el Step o el salto.  

[1 3 5 7]


In [7]:
arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[1, 1:4])  ### Primer indice es la dimension o la matriz. Recordar que inicia en cero. 

[7 8 9]


In [25]:

arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[0:2, 2]) ### De ambos elementos devuelve el indice 2

[3 8]


In [26]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
