Tipos de datos en Python
Por defecto, Python tiene estos tipos de datos:

strings- se utiliza para representar datos de texto, el texto aparece entre comillas. por ejemplo "ABCD"
integer- Se utiliza para representar números enteros. por ejemplo -1, -2, -3
float- utilizado para representar números reales. por ejemplo, 1,2, 42,42
boolean- utilizado para representar Verdadero o Falso.
complex- utilizado para representar números complejos. por ejemplo, 1,0 + 2,0j, 1,5 + 2,5j

Tipos de datos en NumPy
NumPy tiene algunos tipos de datos adicionales y se refiere a tipos de datos con un carácter, como i = números enteros, u = números enteros sin signo, etc.

A continuación se muestra una lista de todos los tipos de datos en NumPy y los caracteres utilizados para representarlos.

i- número entero
b- booleano
u- entero sin signo
f- flotar
c- flotador complejo
m- delta de tiempo
M- fecha y hora
O- objeto
S- cadena
U- cadena unicode
V- fragmento fijo de memoria para otro tipo (nulo)

In [10]:
### Comprobar el tipo de dato de una matriz

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

int64


In [11]:
### Ejemplo de una matriz que contiene cadenas

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [3]:
### Crear matrices con un tipo de dato definido

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [6]:
import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')

Conversión de tipos de datos en matrices existentes
La mejor manera de cambiar el tipo de datos de una matriz existente es hacer una copia de la matriz con el astype()método.

La astype()función crea una copia de la matriz y le permite especificar el tipo de datos como parámetro.

El tipo de datos se puede especificar usando una cadena, como 'f'flotante, 'i'entero, etc. o puede usar el tipo de datos directamente como floatflotante y intentero.



In [13]:
### Ejemplo Cambie el tipo de datos de flotante a entero usando 'i'como valor de parámetro:

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)
print(newarr.base)

[1 2 3]
int32
None


In [14]:
### Ejemplo Cambie el tipo de datos de flotante a entero usando "int" como valor de parámetro:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)
print(newarr.base)

[1 2 3]
int64
None


In [15]:
### Ejemplo Cambie el tipo de datos de entero a booleano:

import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)



[ True False  True]
bool


In [ ]:
 - 