Buscando matrices
Puede buscar en una matriz un valor determinado y devolver los índices que coinciden.

Para buscar una matriz, utilice el where()método.

In [10]:
## Ejemplo obtenga su propio servidor Python
## Encuentre los índices donde el valor es 4:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

## El ejemplo anterior devolverá una tupla:(array([3, 5, 6],)

### Lo que significa que el valor 4 está presente en los índices 3, 5 y 6.


(array([3, 5, 6]),)


In [ ]:
### Encuentre los """indices"" donde los valores son pares

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [3]:
### Encuentre los """indices"" donde los valores son inpares
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


Búsqueda ordenada
Existe un método llamado searchsorted()que realiza una búsqueda binaria en la matriz y devuelve el índice donde se insertaría el valor especificado para mantener el orden de búsqueda.

Se supone que el searchsorted()método se utiliza en matrices ordenadas.

In [4]:
### Ejemplo : Encuentre los índices donde se debe insertar el valor 7:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Ejemplo explicado: el número 7 debe insertarse en el índice 1 para seguir siendo el orden de clasificación.

El método inicia la búsqueda desde la izquierda y devuelve el primer índice donde el número 7 ya no es mayor que el siguiente valor.

Buscar desde el lado derecho
De forma predeterminada, se devuelve el índice más a la izquierda, pero side='right'en su lugar podemos devolver el índice más a la derecha.

In [12]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

### Ejemplo explicado: el número 7 debe insertarse en el índice 2 para seguir siendo el orden de clasificación.

### El método inicia la búsqueda desde la derecha y devuelve el primer índice donde el número 7 ya no es menor que el siguiente valor.


2


Múltiples valores
Para buscar más de un valor, utilice una matriz con los valores especificados.

Ejemplo
Encuentre los índices donde se deben insertar los valores 2, 4 y 6:

In [15]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [17]:
print(x)

[1 2 3]


2