The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [6]:
### Ejemplo de COPY en un Array

import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.copy() ### Se copia el array
arr[0] = 42  ### Modificamos el array original, reemplazando la posicion cero, por el valor 42
print(arr) ### Imprimimos el array modificado
print(x) ### El array que copiamos se concerva igual. no se afecta


[42  2  3  4  5]
[1 2 3 4 5]


In [7]:
### Ejemplo de un VIEW en un array

import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

### En este caso ambos array son afectados por el cambio.

[42  2  3  4  5]
[42  2  3  4  5]


In [9]:
### Hacer cambios en el Array VIEW

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

### Al igual que el anterior ambos cambios afectan el array original y el tipo VIEW

[31  2  3  4  5]
[31  2  3  4  5]


Compruebe si Array posee sus datos
Como se mencionó anteriormente, las copias son propietarias de los datos y las vistas no son propietarias de los datos, pero ¿cómo podemos verificar esto?

Cada matriz NumPy tiene el atributo base que devuelve None si la matriz posee los datos.

De lo contrario, el base  atributo se refiere al objeto original.

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base) ### Devuelve none, por que el array posee los datos
print(y.base) ### Devuelve el array no posee los datos originales

None
[1 2 3 4 5]
