NumPy Array Shape
Shape of an Array
The shape of an array is the number of elements in each dimension.

Obtener la forma de una matriz
Las matrices NumPy tienen un atributo llamado shape que devuelve una tupla y cada índice tiene el número de elementos correspondientes.

In [1]:
### Imprimir la forma de una matriz 2D

import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

### El ejemplo anterior devuelve (2, 4), lo que significa que la matriz tiene 2 dimensiones,
### donde la primera dimensión tiene 2 elementos y la segunda tiene 4

(2, 4)


In [3]:
### Otro Ejemplo
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)

(3, 4)


In [29]:
### Otro Ejemplo con 3 dimensiones.
import numpy as np

arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr.shape)
print(arr.ndim) ### Recordar que este parametro devuelve el numero de dimensiones de una matriz
print(arr)


### En este caso devuelve (2,3,4), lo que significa que la matriz tiene 3 dimensiones
### done la primera dimension tiene 2 elementos, la segunda 3 y la tercera tiene 4

(2, 3, 4)
3
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [10]:
### Otro Ejemplo con 4 dimensiones.

arr = np.array([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]])
print(arr.shape)
print(arr.ndim) ### Recordar que este parametro devuelve el numero de dimensiones de una matriz
### La misma interpretacion del ejercicio anterior.
print(arr)

(2, 2, 3, 4)
4
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]]]


In [12]:
### Usando la manera abreviada para crear matrices de N dimensiones . En este ejemplo 5 dimensiones

import numpy as np

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("shape of array: ", arr.shape)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
shape of array:  (1, 1, 1, 1, 4)
5


In [14]:
### Creando matriz de 5 dimensiones sin abreviar.

arr = np.array([[[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]],[[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]],[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[1,2,3,4],[5,6,7,8],[9,10,11,12]]]]])
print("shape of array : ",arr.shape)
print("dimension of array : ", arr.ndim) ### Recordar que este parametro devuelve el numero de dimensiones de una matriz
### La misma interpretacion del ejercicio anterior.
print(arr)

shape of array :  (2, 2, 2, 3, 4)
dimension of array :  5
[[[[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]

   [[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]]


  [[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]

   [[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]]]



 [[[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]

   [[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]]


  [[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]

   [[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]]]]]


In [31]:
for x in arr:
  print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
for x in arr:
  for y in x:
      for z in y:
          for l in z:
              for k in l:
                print(k)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [26]:
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [27]:
import numpy as np

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


In [28]:
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 2) 3
(0, 0, 0, 0, 3) 4
(0, 0, 0, 1, 0) 5
(0, 0, 0, 1, 1) 6
(0, 0, 0, 1, 2) 7
(0, 0, 0, 1, 3) 8
(0, 0, 0, 2, 0) 9
(0, 0, 0, 2, 1) 10
(0, 0, 0, 2, 2) 11
(0, 0, 0, 2, 3) 12
(0, 0, 1, 0, 0) 1
(0, 0, 1, 0, 1) 2
(0, 0, 1, 0, 2) 3
(0, 0, 1, 0, 3) 4
(0, 0, 1, 1, 0) 5
(0, 0, 1, 1, 1) 6
(0, 0, 1, 1, 2) 7
(0, 0, 1, 1, 3) 8
(0, 0, 1, 2, 0) 9
(0, 0, 1, 2, 1) 10
(0, 0, 1, 2, 2) 11
(0, 0, 1, 2, 3) 12
(0, 1, 0, 0, 0) 1
(0, 1, 0, 0, 1) 2
(0, 1, 0, 0, 2) 3
(0, 1, 0, 0, 3) 4
(0, 1, 0, 1, 0) 5
(0, 1, 0, 1, 1) 6
(0, 1, 0, 1, 2) 7
(0, 1, 0, 1, 3) 8
(0, 1, 0, 2, 0) 9
(0, 1, 0, 2, 1) 10
(0, 1, 0, 2, 2) 11
(0, 1, 0, 2, 3) 12
(0, 1, 1, 0, 0) 1
(0, 1, 1, 0, 1) 2
(0, 1, 1, 0, 2) 3
(0, 1, 1, 0, 3) 4
(0, 1, 1, 1, 0) 5
(0, 1, 1, 1, 1) 6
(0, 1, 1, 1, 2) 7
(0, 1, 1, 1, 3) 8
(0, 1, 1, 2, 0) 9
(0, 1, 1, 2, 1) 10
(0, 1, 1, 2, 2) 11
(0, 1, 1, 2, 3) 12
(1, 0, 0, 0, 0) 1
(1, 0, 0, 0, 1) 2
(1, 0, 0, 0, 2) 3
(1, 0, 0, 0, 3) 4
(1, 0, 0, 1, 0) 5
(1, 0, 0, 1, 1) 6
(1, 0, 0, 1, 2) 