Iterando matrices
Iterar significa recorrer elementos uno por uno.

Mientras tratamos con matrices multidimensionales en numpy, podemos hacerlo usando forun bucle básico de Python.

Si iteramos en una matriz 1-D, pasará por cada elemento uno por uno.

In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [2]:
### Iterando Matrices 2D
### En una matriz 2-D, pasará por todas las filas.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

# Si iteramos en una matriz n -D, pasará por la dimensión n-1 una por una.

[1 2 3]
[4 5 6]


In [4]:
### Para devolver los valores reales, los escalares, tenemos que iterar las matrices en cada dimensión
# Ejemplo Iterar sobre cada elemento escalar de la matriz 2-D:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)


1
2
3
4
5
6


In [5]:
### Iterando Matrices 2D
### En una matriz 3-D, pasará por todas las Matrices 2D.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
# Para devolver los valores reales, los escalares, tenemos que iterar las matrices en cada dimensión.
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


Iterando matrices usando nditer()
La función nditer()es una función de ayuda que se puede utilizar desde iteraciones muy básicas hasta iteraciones muy avanzadas. Resuelve algunos problemas básicos que enfrentamos en la iteración, repasémoslo con ejemplos.

Iterando en cada elemento escalar
En for los bucles básicos, al iterar a través de cada escalar de una matriz, necesitamos usar n for bucles que pueden ser difíciles de escribir para matrices con una dimensionalidad muy alta.

In [7]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


Matriz iterativa con diferentes tipos de datos
Podemos usar op_dtypes un argumento y pasarle el tipo de datos esperado para cambiar el tipo de datos de los elementos mientras iteramos.

NumPy no cambia el tipo de datos del elemento en el lugar (donde el elemento está en una matriz), por lo que necesita otro espacio para realizar esta acción, ese espacio adicional se llama buffer, y para habilitarlo nditer()pasamos flags=['buffered'].

In [15]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

print(x.base)
    ### Buffered es el espacio que requiere para hacer el cambio del tipo de dato.  op_types especifica a que tipo de dato queremos cambiar.

b'1'
b'2'
b'3'


In [11]:
#Iterando con diferentes tamaños de paso
#Podemos usar filtrado y seguido de iteración.

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]): ## El primer argumento indica de la primera dimension tomar todo desde el inio hasta el final
    ## despues de la coma indica la segunda dimension, que indica tomar todo de cada grupo y el tercer argumento (2), corresponde al step.
  print(x)

1
3
5
7


Iteración enumerada usando ndenumerate()
Enumeración significa mencionar el número de secuencia de algo uno por uno.

A veces requerimos el índice correspondiente del elemento mientras iteramos, el ndenumerate()método se puede utilizar para esos casos de uso.

In [13]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
### Ejemplo Enumere los siguientes elementos de la matriz 2D:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
