Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.
______

Unirse a matrices NumPy
Unir significa poner el contenido de dos o más matrices en una sola matriz.

En SQL unimos tablas en función de una clave, mientras que en NumPy unimos arrays por ejes.

Pasamos una secuencia de arrays que queremos unir a la concatenate()función, junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.

In [7]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
### Ejemplo unir dos matrices 2-D a lo largo de filas (eje=1)
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
print(arr.ndim)

[[1 2 5 6]
 [3 4 7 8]]
2


Unir matrices usando funciones de pila
El apilamiento es lo mismo que la concatenación, la única diferencia es que el apilamiento se realiza a lo largo de un nuevo eje.

Podemos concatenar dos matrices 1-D a lo largo del segundo eje, lo que daría como resultado colocarlas una sobre la otra, es decir. apilado.

Pasamos una secuencia de arrays que queremos unir al stack()método junto con el eje. Si el eje no se pasa explícitamente, se toma como 0.

In [24]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)
print(arr.ndim)

[[1 4]
 [2 5]
 [3 6]]
2


In [14]:
#Apilado a lo largo de filas
# NumPy proporciona una función auxiliar: hstack() apilar a lo largo de filas.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [22]:
#Apilado a lo largo de columnas
# NumPy proporciona una función auxiliar: vstack()  apilar a lo largo de columnas.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
## Apilado a lo largo de la altura (Profundidad)
# NumPy proporciona una función auxiliar: dstack() apilar a lo largo de la altura, que es lo mismo que la profundidad.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
